MeuProjeto/MeuSite/MeuSite/urls.py
from django.contrib import admin
from django.urls import path
from MeuSite import views
from django.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home, name="home"),
    path('curriculo/', include('curriculo.urls')),
]

MeuProjeto/MeuSite/curriculo/urls.py
from django.urls import path    
from . import views

app_name = 'curriculo'

urlpatterns = [
    path('meucurriculo/', views.meucurriculo, name='meucurriculo'),
    path('curriculospiff/', views.curriculospiff, name='curriculospiff'),
]

MeuProjeto/MeuSite/curriculo/models.py
from django.db import models

# Create your models here.

MeuProjeto/MeuSite/MeuSite/views.py
from django.shortcuts import render

def home(request):
    '''
    View function for home page of site.
    Renders the home.html template.
    '''
    return render(request, 'MeuSite/home.html')

MeuProjeto/MeuSite/curriculo/views.py
from django.shortcuts import render

# Create your views here.
def meucurriculo(request):
    return render(request, 'curriculo/meucurriculo.html')
def curriculospiff(request):
    return render(request, 'curriculo/curriculospiff.html')     

MeuProjeto/MeuSite/MeuSite/templates/MeuSite/home.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>meu nome é sofia, tenho 18 anos e estou aprendendo Django!</h1>
    Sou de angra dos reis e  estou cursando engenharia de producao na puc rio
    <h2>Links para os curriculos</h2>
    <a href="{% url 'curriculo:meucurriculo' %}">Meu curriculo</a><br>
    <a href="{% url 'curriculo:curriculospiff' %}">Curriculo do Spiff</a>
</body>
</html>

MeuProjeto/MeuSite/curriculo/templates/curriculo/curriculospiff.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
        <link rel="stylesheet" href="{% static 'curriculo/css/curriculo.css' %}">        <link href="https://fonts.googleapis.com/css2?family=Orbitron&display=swap" rel="stylesheet">
    </head>
<body>
    <section titulo='titulo'>
    <h1>Astronauta Intergalático</h1>
<nav class="navegacao">Menu Estelar
<a href="http://www.puc-rio.br">PUC-Rio</a>
<a href="#resumo">Resumo</a> 
Habilidades
Educação
Idiomas
Versão 2
<a href="meu-curriculo.html">Meu currículo</a> </nav> 
<main>
    <section lista='lista'>
<h2>Astronauta Spiff</h2>
<div id='sumario'>
    <p><ul><li>Profissão:Astronauta Intergalático</li><li>Explorador de Mundos Desconhecidos</li>
<li>Base Principal: Quarto Secreto, Subúrbio da Terra, Sistema Solar</li>
<li>Comunicações (ocasionalmente interceptadas): (55) 21 99999-Spiff</li>
<li> Secreto: spiff.the.explorer@galaxymail.com (altamente criptografado)</li></ul></p></div>
Um intrépido e imaginativo astronauta com vasta experiência em exploração espacial solo e em missões críticas a planetas inóspitos. Proficiente em pilotagem de naves espaciais de construção própria, análise de fenômenos alienígenas e resolução criativa de problemas em ambientes extraterrestres. Possui um histórico comprovado de descobertas notáveis e encontros (nem sempre amigáveis) com formas de vida alienígenas diversas.
<section id="texto">
<p>Experiência Profissional
Astronauta Intergalático e Comandante de Missão Solo
Várias Expedições (Contínuo) civilizações ameaçadas por buracos negros.
Vice-campeão intergalático de cara-coroa.
Habilidades Técnicas Espaciais
Acrobacias em gravidade zero
Comunicação interespécies
Construção de bases lunares improvisadas
Voo solo de espaçonaves
Negociação com espécies extraterrestres
Treinamento de resistência contra gravidade zero
Pilotagem de espaçonaves não convencionais
Navegação interestelar (baseada principalmente em intuição e mapas estelares desenhados à mão)
Reparos de emergência em gravidade zero (com recursos limitados)
Análise de atmosferas alienígenas (método: "cheirar e ver")
Comunicação interestelar básica (incluindo gestos e sons estranhos)
Sobrevivência em ambientes hostis
Manutenção de propulsores a jato improvisados
Habilidades Pessoais
Imaginação hiperativa
Pensamento criativo e resolução de problemas não convencionais
Determinação inabalável (especialmente quando motivado por recompensas espaciais)
Adaptabilidade a situações inesperadas (que são quase todas)
Autoconfiança (às vezes excessiva)</p>
<p>Habilidade de argumentação persuasiva (especialmente com figuras de autoridade terrestres)
Educação (AutoPilotou e manteve diversas naves espaciais de design exclusivo, incluindo a "Destruidora de Cartazes" e a "Vingadora de Júpiter".
Realizou extensas pesquisas em planetas desconhecidos, catalogando flora, fauna e geologia exóticas (muitas vezes com resultados surpreendentes).
Desenvolveu protocolos de comunicação rudimentares com várias espécies alienígenas (com sucesso variável).
Sobreviveu a condições ambientais extremas, incluindo tempestades de glitter cósmico e campos gravitacionais instáveis.
Documentou descobertas científicas inovadoras, incluindo a existência de "Smoggles" e a natureza da "Energia Zum-Zum".
Infiltrou em planetas hostis.
Resgatou de missões espaciais perdidas.
Descobriu de novos sistemas estelares.
Explorou e mapeou planetas inexplorados.
Combateu contra hordas de alienígenas hostis.
Resgatou de-Didata e Experiencial)
Doutorado em Exploração Interdimensional e Defesa Contra Alienígenas Malignos (Honras Imaginárias)
Mestrado em Viagem Hiperespacial (com honras)
Universidade Estelar de Calvin — Ciências da Galáxia
Academia Estelar de Calvin — Diploma em Engenharia Espacial e Aventuras
Currículo incluiu estudos avançados em:
Teoria da Propulsão a Jato de Papelão
Linguística Alienígena Intuitiva
Táticas de Fuga e Evasão Escolar Espacial
Astronomia de Quintal Avançada
Sobrevivência com Lancheiras e Suco de Limão
Idiomas
Terráqueo
Glurpiano
Dialetos de Saturno</p>
</section>
<table>
    <thead>
        <tr>
            <th> ENG4010</th>
            <th> CRE1200</th>
            <th> CTC4001</th>
            <th> CTC4002</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td> Projeto integrado sustentabilidade</td>
            <td> Jesus</td>
            <td> Intrumentacao e medicao</td>
            <td> Modelagem e programacao</td>
        </tr>
        <tr>
            <td> 2025.1</td>
            <td> 2025.1</td>
            <td> 2025.1</td>
            <td> 2025.1</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td> Isabel</td>
            <td> Marco</td>
            <td> Carlos</td>
            <td> Joisa e Felipe</td>
        </tr>
    </tfoot>
</table>
</main>
<footer>"Nenhum alienígena fica para trás... porque eu desintegro todos!"</footer>
<section imagens="imagens">
<br><img src='{% static "curriculo/img/spiff.jpeg" %}'>
<section lista="lista">
<ol><li>ENG4021</li><li>Projeto de software</li><li>2025.2</li><li>Alexandre Meslin</li></ol>
</body>
</html>

MeuProjeto/MeuSite/curriculo/templates/curriculo/meucurriculo.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <link rel="stylesheet" href="{% static 'curriculo/css/meucurriculo.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Meu curriculo</h1>
    <section id="foto">
        <h2>Sofia Rafful de Carvalho</h2>
    <br><img id="fotosofia" src='https://mail.google.com/mail/u/0?ui=2&ik=5e3f3c79ae&attid=0.1&permmsgid=msg-a:r1583499299820559708&th=199cddfc7dc9d1df&view=fimg&fur=ip&permmsgid=msg-a:r1583499299820559708&sz=s0-l75-ft&attbid=ANGjdJ9W-PYX4QCTwdbv2o0vxXJOLn6XNUBiG_9-AaMO6gh1wY5SFiUtUDLgyYPEVP3WgvnJEIXaLQ9LChrtwW8nvD9RpPVZMb04WEDrJDibq0FMjxNKCXd6pUCr_-o&disp=emb&realattid=ii_199cddfa4e02e03e5dc1&zw'></section>
    <section id="lista>"
    <h2>Habilidades</h2>
    <p><ul><li>Raciocinio logico</li>
        <li>Trabalhar em grupo</li>
        <li>Planejamento</li>
        <li>Organizacao</li></ul></p></section>
<section id="educacao">
<h3>Materias ja cursadas</h3>
<table>
    <thead>
        <tr>
            <th> ENG4010</th>
            <th> CRE1200</th>
            <th> CTC4001</th>
            <th> CTC4002</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td> Projeto integrado sustentabilidade</td>
            <td> Jesus</td>
            <td> Intrumentacao e medicao</td>
            <td> Modelagem e programacao</td>
        </tr>
        <tr>
            <td> 2025.1</td>
            <td> 2025.1</td>
            <td> 2025.1</td>
            <td> 2025.1</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <td> Isabel</td>
            <td> Marco</td>
            <td> Carlos</td>
            <td> Joisa e Felipe</td>
        </tr>
    </tfoot>
</table>
<section id="links"></section>
<a href="index.html">Curriculo do meu amigo Spiff</a></section>
<a href="http://www.puc-rio.br">PUC-Rio</a>
</body>
</html>